//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SYSGERModel", "FK_recrutements_domaine_ref", "domaine_ref", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SYSGER.Model.domaine_ref), "recrutements", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SYSGER.Model.recrutement), true)]
[assembly: EdmRelationshipAttribute("SYSGERModel", "FK_recrutements_niveau_education_ref", "niveau_education_ref", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SYSGER.Model.niveau_education_ref), "recrutements", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SYSGER.Model.recrutement), true)]
[assembly: EdmRelationshipAttribute("SYSGERModel", "FK_recrutements_niveau_ref", "niveau_ref", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SYSGER.Model.niveau_ref), "recrutements", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SYSGER.Model.recrutement), true)]
[assembly: EdmRelationshipAttribute("SYSGERModel", "FK_recrutements_niveau_ref1", "niveau_ref", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SYSGER.Model.niveau_ref), "recrutements", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SYSGER.Model.recrutement), true)]
[assembly: EdmRelationshipAttribute("SYSGERModel", "FK_recrutements_position_ref", "position_ref", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SYSGER.Model.position_ref), "recrutements", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SYSGER.Model.recrutement), true)]

#endregion

namespace SYSGER.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SYSGEREntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SYSGEREntities object using the connection string found in the 'SYSGEREntities' section of the application configuration file.
        /// </summary>
        public SYSGEREntities() : base("name=SYSGEREntities", "SYSGEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SYSGEREntities object.
        /// </summary>
        public SYSGEREntities(string connectionString) : base(connectionString, "SYSGEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SYSGEREntities object.
        /// </summary>
        public SYSGEREntities(EntityConnection connection) : base(connection, "SYSGEREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<domaine_ref> domaine_ref
        {
            get
            {
                if ((_domaine_ref == null))
                {
                    _domaine_ref = base.CreateObjectSet<domaine_ref>("domaine_ref");
                }
                return _domaine_ref;
            }
        }
        private ObjectSet<domaine_ref> _domaine_ref;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<niveau_education_ref> niveau_education_ref
        {
            get
            {
                if ((_niveau_education_ref == null))
                {
                    _niveau_education_ref = base.CreateObjectSet<niveau_education_ref>("niveau_education_ref");
                }
                return _niveau_education_ref;
            }
        }
        private ObjectSet<niveau_education_ref> _niveau_education_ref;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<niveau_ref> niveau_ref
        {
            get
            {
                if ((_niveau_ref == null))
                {
                    _niveau_ref = base.CreateObjectSet<niveau_ref>("niveau_ref");
                }
                return _niveau_ref;
            }
        }
        private ObjectSet<niveau_ref> _niveau_ref;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<position_ref> position_ref
        {
            get
            {
                if ((_position_ref == null))
                {
                    _position_ref = base.CreateObjectSet<position_ref>("position_ref");
                }
                return _position_ref;
            }
        }
        private ObjectSet<position_ref> _position_ref;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<recrutement> recrutements
        {
            get
            {
                if ((_recrutements == null))
                {
                    _recrutements = base.CreateObjectSet<recrutement>("recrutements");
                }
                return _recrutements;
            }
        }
        private ObjectSet<recrutement> _recrutements;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the domaine_ref EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodomaine_ref(domaine_ref domaine_ref)
        {
            base.AddObject("domaine_ref", domaine_ref);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the niveau_education_ref EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToniveau_education_ref(niveau_education_ref niveau_education_ref)
        {
            base.AddObject("niveau_education_ref", niveau_education_ref);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the niveau_ref EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToniveau_ref(niveau_ref niveau_ref)
        {
            base.AddObject("niveau_ref", niveau_ref);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the position_ref EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToposition_ref(position_ref position_ref)
        {
            base.AddObject("position_ref", position_ref);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the recrutements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorecrutements(recrutement recrutement)
        {
            base.AddObject("recrutements", recrutement);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYSGERModel", Name="domaine_ref")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class domaine_ref : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new domaine_ref object.
        /// </summary>
        /// <param name="domaineID">Initial value of the domaineID property.</param>
        public static domaine_ref Createdomaine_ref(global::System.Int32 domaineID)
        {
            domaine_ref domaine_ref = new domaine_ref();
            domaine_ref.domaineID = domaineID;
            return domaine_ref;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 domaineID
        {
            get
            {
                return _domaineID;
            }
            set
            {
                if (_domaineID != value)
                {
                    OndomaineIDChanging(value);
                    ReportPropertyChanging("domaineID");
                    _domaineID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("domaineID");
                    OndomaineIDChanged();
                }
            }
        }
        private global::System.Int32 _domaineID;
        partial void OndomaineIDChanging(global::System.Int32 value);
        partial void OndomaineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String domaine_Desc
        {
            get
            {
                return _domaine_Desc;
            }
            set
            {
                Ondomaine_DescChanging(value);
                ReportPropertyChanging("domaine_Desc");
                _domaine_Desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("domaine_Desc");
                Ondomaine_DescChanged();
            }
        }
        private global::System.String _domaine_Desc;
        partial void Ondomaine_DescChanging(global::System.String value);
        partial void Ondomaine_DescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creation_user
        {
            get
            {
                return _creation_user;
            }
            set
            {
                Oncreation_userChanging(value);
                ReportPropertyChanging("creation_user");
                _creation_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creation_user");
                Oncreation_userChanged();
            }
        }
        private global::System.String _creation_user;
        partial void Oncreation_userChanging(global::System.String value);
        partial void Oncreation_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> creation_date
        {
            get
            {
                return _creation_date;
            }
            set
            {
                Oncreation_dateChanging(value);
                ReportPropertyChanging("creation_date");
                _creation_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("creation_date");
                Oncreation_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _creation_date;
        partial void Oncreation_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreation_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String update_user
        {
            get
            {
                return _update_user;
            }
            set
            {
                Onupdate_userChanging(value);
                ReportPropertyChanging("update_user");
                _update_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("update_user");
                Onupdate_userChanged();
            }
        }
        private global::System.String _update_user;
        partial void Onupdate_userChanging(global::System.String value);
        partial void Onupdate_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date
        {
            get
            {
                return _update_date;
            }
            set
            {
                Onupdate_dateChanging(value);
                ReportPropertyChanging("update_date");
                _update_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date");
                Onupdate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date;
        partial void Onupdate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_domaine_ref", "recrutements")]
        public EntityCollection<recrutement> recrutements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_domaine_ref", "recrutements");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_domaine_ref", "recrutements", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYSGERModel", Name="niveau_education_ref")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class niveau_education_ref : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new niveau_education_ref object.
        /// </summary>
        /// <param name="niveauEducationID">Initial value of the niveauEducationID property.</param>
        public static niveau_education_ref Createniveau_education_ref(global::System.String niveauEducationID)
        {
            niveau_education_ref niveau_education_ref = new niveau_education_ref();
            niveau_education_ref.niveauEducationID = niveauEducationID;
            return niveau_education_ref;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String niveauEducationID
        {
            get
            {
                return _niveauEducationID;
            }
            set
            {
                if (_niveauEducationID != value)
                {
                    OnniveauEducationIDChanging(value);
                    ReportPropertyChanging("niveauEducationID");
                    _niveauEducationID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("niveauEducationID");
                    OnniveauEducationIDChanged();
                }
            }
        }
        private global::System.String _niveauEducationID;
        partial void OnniveauEducationIDChanging(global::System.String value);
        partial void OnniveauEducationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String niveauEducation_Desc
        {
            get
            {
                return _niveauEducation_Desc;
            }
            set
            {
                OnniveauEducation_DescChanging(value);
                ReportPropertyChanging("niveauEducation_Desc");
                _niveauEducation_Desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("niveauEducation_Desc");
                OnniveauEducation_DescChanged();
            }
        }
        private global::System.String _niveauEducation_Desc;
        partial void OnniveauEducation_DescChanging(global::System.String value);
        partial void OnniveauEducation_DescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creation_user
        {
            get
            {
                return _creation_user;
            }
            set
            {
                Oncreation_userChanging(value);
                ReportPropertyChanging("creation_user");
                _creation_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creation_user");
                Oncreation_userChanged();
            }
        }
        private global::System.String _creation_user;
        partial void Oncreation_userChanging(global::System.String value);
        partial void Oncreation_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> creation_date
        {
            get
            {
                return _creation_date;
            }
            set
            {
                Oncreation_dateChanging(value);
                ReportPropertyChanging("creation_date");
                _creation_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("creation_date");
                Oncreation_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _creation_date;
        partial void Oncreation_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreation_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String update_user
        {
            get
            {
                return _update_user;
            }
            set
            {
                Onupdate_userChanging(value);
                ReportPropertyChanging("update_user");
                _update_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("update_user");
                Onupdate_userChanged();
            }
        }
        private global::System.String _update_user;
        partial void Onupdate_userChanging(global::System.String value);
        partial void Onupdate_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date
        {
            get
            {
                return _update_date;
            }
            set
            {
                Onupdate_dateChanging(value);
                ReportPropertyChanging("update_date");
                _update_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date");
                Onupdate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date;
        partial void Onupdate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_niveau_education_ref", "recrutements")]
        public EntityCollection<recrutement> recrutements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_niveau_education_ref", "recrutements");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_niveau_education_ref", "recrutements", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYSGERModel", Name="niveau_ref")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class niveau_ref : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new niveau_ref object.
        /// </summary>
        /// <param name="niveauID">Initial value of the niveauID property.</param>
        public static niveau_ref Createniveau_ref(global::System.String niveauID)
        {
            niveau_ref niveau_ref = new niveau_ref();
            niveau_ref.niveauID = niveauID;
            return niveau_ref;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String niveauID
        {
            get
            {
                return _niveauID;
            }
            set
            {
                if (_niveauID != value)
                {
                    OnniveauIDChanging(value);
                    ReportPropertyChanging("niveauID");
                    _niveauID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("niveauID");
                    OnniveauIDChanged();
                }
            }
        }
        private global::System.String _niveauID;
        partial void OnniveauIDChanging(global::System.String value);
        partial void OnniveauIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String niveau_Desc
        {
            get
            {
                return _niveau_Desc;
            }
            set
            {
                Onniveau_DescChanging(value);
                ReportPropertyChanging("niveau_Desc");
                _niveau_Desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("niveau_Desc");
                Onniveau_DescChanged();
            }
        }
        private global::System.String _niveau_Desc;
        partial void Onniveau_DescChanging(global::System.String value);
        partial void Onniveau_DescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creation_user
        {
            get
            {
                return _creation_user;
            }
            set
            {
                Oncreation_userChanging(value);
                ReportPropertyChanging("creation_user");
                _creation_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creation_user");
                Oncreation_userChanged();
            }
        }
        private global::System.String _creation_user;
        partial void Oncreation_userChanging(global::System.String value);
        partial void Oncreation_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> creation_date
        {
            get
            {
                return _creation_date;
            }
            set
            {
                Oncreation_dateChanging(value);
                ReportPropertyChanging("creation_date");
                _creation_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("creation_date");
                Oncreation_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _creation_date;
        partial void Oncreation_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreation_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String update_user
        {
            get
            {
                return _update_user;
            }
            set
            {
                Onupdate_userChanging(value);
                ReportPropertyChanging("update_user");
                _update_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("update_user");
                Onupdate_userChanged();
            }
        }
        private global::System.String _update_user;
        partial void Onupdate_userChanging(global::System.String value);
        partial void Onupdate_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date
        {
            get
            {
                return _update_date;
            }
            set
            {
                Onupdate_dateChanging(value);
                ReportPropertyChanging("update_date");
                _update_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date");
                Onupdate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date;
        partial void Onupdate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_niveau_ref", "recrutements")]
        public EntityCollection<recrutement> recrutements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_niveau_ref", "recrutements");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_niveau_ref", "recrutements", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_niveau_ref1", "recrutements")]
        public EntityCollection<recrutement> recrutements1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_niveau_ref1", "recrutements");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_niveau_ref1", "recrutements", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYSGERModel", Name="position_ref")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class position_ref : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new position_ref object.
        /// </summary>
        /// <param name="positionID">Initial value of the positionID property.</param>
        public static position_ref Createposition_ref(global::System.Int32 positionID)
        {
            position_ref position_ref = new position_ref();
            position_ref.positionID = positionID;
            return position_ref;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 positionID
        {
            get
            {
                return _positionID;
            }
            set
            {
                if (_positionID != value)
                {
                    OnpositionIDChanging(value);
                    ReportPropertyChanging("positionID");
                    _positionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("positionID");
                    OnpositionIDChanged();
                }
            }
        }
        private global::System.Int32 _positionID;
        partial void OnpositionIDChanging(global::System.Int32 value);
        partial void OnpositionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String positions_Desc
        {
            get
            {
                return _positions_Desc;
            }
            set
            {
                Onpositions_DescChanging(value);
                ReportPropertyChanging("positions_Desc");
                _positions_Desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("positions_Desc");
                Onpositions_DescChanged();
            }
        }
        private global::System.String _positions_Desc;
        partial void Onpositions_DescChanging(global::System.String value);
        partial void Onpositions_DescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creation_user
        {
            get
            {
                return _creation_user;
            }
            set
            {
                Oncreation_userChanging(value);
                ReportPropertyChanging("creation_user");
                _creation_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creation_user");
                Oncreation_userChanged();
            }
        }
        private global::System.String _creation_user;
        partial void Oncreation_userChanging(global::System.String value);
        partial void Oncreation_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> creation_date
        {
            get
            {
                return _creation_date;
            }
            set
            {
                Oncreation_dateChanging(value);
                ReportPropertyChanging("creation_date");
                _creation_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("creation_date");
                Oncreation_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _creation_date;
        partial void Oncreation_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreation_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String update_user
        {
            get
            {
                return _update_user;
            }
            set
            {
                Onupdate_userChanging(value);
                ReportPropertyChanging("update_user");
                _update_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("update_user");
                Onupdate_userChanged();
            }
        }
        private global::System.String _update_user;
        partial void Onupdate_userChanging(global::System.String value);
        partial void Onupdate_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date
        {
            get
            {
                return _update_date;
            }
            set
            {
                Onupdate_dateChanging(value);
                ReportPropertyChanging("update_date");
                _update_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date");
                Onupdate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date;
        partial void Onupdate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_position_ref", "recrutements")]
        public EntityCollection<recrutement> recrutements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_position_ref", "recrutements");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recrutement>("SYSGERModel.FK_recrutements_position_ref", "recrutements", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYSGERModel", Name="recrutement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recrutement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new recrutement object.
        /// </summary>
        /// <param name="recrutementID">Initial value of the recrutementID property.</param>
        public static recrutement Createrecrutement(global::System.Int64 recrutementID)
        {
            recrutement recrutement = new recrutement();
            recrutement.recrutementID = recrutementID;
            return recrutement;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 recrutementID
        {
            get
            {
                return _recrutementID;
            }
            set
            {
                if (_recrutementID != value)
                {
                    OnrecrutementIDChanging(value);
                    ReportPropertyChanging("recrutementID");
                    _recrutementID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recrutementID");
                    OnrecrutementIDChanged();
                }
            }
        }
        private global::System.Int64 _recrutementID;
        partial void OnrecrutementIDChanging(global::System.Int64 value);
        partial void OnrecrutementIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String refID
        {
            get
            {
                return _refID;
            }
            set
            {
                OnrefIDChanging(value);
                ReportPropertyChanging("refID");
                _refID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("refID");
                OnrefIDChanged();
            }
        }
        private global::System.String _refID;
        partial void OnrefIDChanging(global::System.String value);
        partial void OnrefIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dateNaissance
        {
            get
            {
                return _dateNaissance;
            }
            set
            {
                OndateNaissanceChanging(value);
                ReportPropertyChanging("dateNaissance");
                _dateNaissance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateNaissance");
                OndateNaissanceChanged();
            }
        }
        private Nullable<global::System.DateTime> _dateNaissance;
        partial void OndateNaissanceChanging(Nullable<global::System.DateTime> value);
        partial void OndateNaissanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private Nullable<global::System.Int32> _age;
        partial void OnageChanging(Nullable<global::System.Int32> value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone1
        {
            get
            {
                return _phone1;
            }
            set
            {
                Onphone1Changing(value);
                ReportPropertyChanging("phone1");
                _phone1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone1");
                Onphone1Changed();
            }
        }
        private global::System.String _phone1;
        partial void Onphone1Changing(global::System.String value);
        partial void Onphone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone2
        {
            get
            {
                return _phone2;
            }
            set
            {
                Onphone2Changing(value);
                ReportPropertyChanging("phone2");
                _phone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone2");
                Onphone2Changed();
            }
        }
        private global::System.String _phone2;
        partial void Onphone2Changing(global::System.String value);
        partial void Onphone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> domaineID
        {
            get
            {
                return _domaineID;
            }
            set
            {
                OndomaineIDChanging(value);
                ReportPropertyChanging("domaineID");
                _domaineID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("domaineID");
                OndomaineIDChanged();
            }
        }
        private Nullable<global::System.Int32> _domaineID;
        partial void OndomaineIDChanging(Nullable<global::System.Int32> value);
        partial void OndomaineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String niveauEducationID
        {
            get
            {
                return _niveauEducationID;
            }
            set
            {
                OnniveauEducationIDChanging(value);
                ReportPropertyChanging("niveauEducationID");
                _niveauEducationID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("niveauEducationID");
                OnniveauEducationIDChanged();
            }
        }
        private global::System.String _niveauEducationID;
        partial void OnniveauEducationIDChanging(global::System.String value);
        partial void OnniveauEducationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String autresCompetences
        {
            get
            {
                return _autresCompetences;
            }
            set
            {
                OnautresCompetencesChanging(value);
                ReportPropertyChanging("autresCompetences");
                _autresCompetences = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("autresCompetences");
                OnautresCompetencesChanged();
            }
        }
        private global::System.String _autresCompetences;
        partial void OnautresCompetencesChanging(global::System.String value);
        partial void OnautresCompetencesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String niveauInformatiqueID
        {
            get
            {
                return _niveauInformatiqueID;
            }
            set
            {
                OnniveauInformatiqueIDChanging(value);
                ReportPropertyChanging("niveauInformatiqueID");
                _niveauInformatiqueID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("niveauInformatiqueID");
                OnniveauInformatiqueIDChanged();
            }
        }
        private global::System.String _niveauInformatiqueID;
        partial void OnniveauInformatiqueIDChanging(global::System.String value);
        partial void OnniveauInformatiqueIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> anneesExperience
        {
            get
            {
                return _anneesExperience;
            }
            set
            {
                OnanneesExperienceChanging(value);
                ReportPropertyChanging("anneesExperience");
                _anneesExperience = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anneesExperience");
                OnanneesExperienceChanged();
            }
        }
        private Nullable<global::System.Int32> _anneesExperience;
        partial void OnanneesExperienceChanging(Nullable<global::System.Int32> value);
        partial void OnanneesExperienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String niveauAnglaisID
        {
            get
            {
                return _niveauAnglaisID;
            }
            set
            {
                OnniveauAnglaisIDChanging(value);
                ReportPropertyChanging("niveauAnglaisID");
                _niveauAnglaisID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("niveauAnglaisID");
                OnniveauAnglaisIDChanged();
            }
        }
        private global::System.String _niveauAnglaisID;
        partial void OnniveauAnglaisIDChanging(global::System.String value);
        partial void OnniveauAnglaisIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> positionID
        {
            get
            {
                return _positionID;
            }
            set
            {
                OnpositionIDChanging(value);
                ReportPropertyChanging("positionID");
                _positionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("positionID");
                OnpositionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _positionID;
        partial void OnpositionIDChanging(Nullable<global::System.Int32> value);
        partial void OnpositionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String statut
        {
            get
            {
                return _statut;
            }
            set
            {
                OnstatutChanging(value);
                ReportPropertyChanging("statut");
                _statut = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("statut");
                OnstatutChanged();
            }
        }
        private global::System.String _statut;
        partial void OnstatutChanging(global::System.String value);
        partial void OnstatutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String refererPar
        {
            get
            {
                return _refererPar;
            }
            set
            {
                OnrefererParChanging(value);
                ReportPropertyChanging("refererPar");
                _refererPar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("refererPar");
                OnrefererParChanged();
            }
        }
        private global::System.String _refererPar;
        partial void OnrefererParChanging(global::System.String value);
        partial void OnrefererParChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creation_user
        {
            get
            {
                return _creation_user;
            }
            set
            {
                Oncreation_userChanging(value);
                ReportPropertyChanging("creation_user");
                _creation_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creation_user");
                Oncreation_userChanged();
            }
        }
        private global::System.String _creation_user;
        partial void Oncreation_userChanging(global::System.String value);
        partial void Oncreation_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> creation_date
        {
            get
            {
                return _creation_date;
            }
            set
            {
                Oncreation_dateChanging(value);
                ReportPropertyChanging("creation_date");
                _creation_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("creation_date");
                Oncreation_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _creation_date;
        partial void Oncreation_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreation_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String update_user
        {
            get
            {
                return _update_user;
            }
            set
            {
                Onupdate_userChanging(value);
                ReportPropertyChanging("update_user");
                _update_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("update_user");
                Onupdate_userChanged();
            }
        }
        private global::System.String _update_user;
        partial void Onupdate_userChanging(global::System.String value);
        partial void Onupdate_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date
        {
            get
            {
                return _update_date;
            }
            set
            {
                Onupdate_dateChanging(value);
                ReportPropertyChanging("update_date");
                _update_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date");
                Onupdate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date;
        partial void Onupdate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sexe
        {
            get
            {
                return _sexe;
            }
            set
            {
                OnsexeChanging(value);
                ReportPropertyChanging("sexe");
                _sexe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sexe");
                OnsexeChanged();
            }
        }
        private global::System.String _sexe;
        partial void OnsexeChanging(global::System.String value);
        partial void OnsexeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_domaine_ref", "domaine_ref")]
        public domaine_ref domaine_ref
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<domaine_ref>("SYSGERModel.FK_recrutements_domaine_ref", "domaine_ref").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<domaine_ref>("SYSGERModel.FK_recrutements_domaine_ref", "domaine_ref").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<domaine_ref> domaine_refReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<domaine_ref>("SYSGERModel.FK_recrutements_domaine_ref", "domaine_ref");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<domaine_ref>("SYSGERModel.FK_recrutements_domaine_ref", "domaine_ref", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_niveau_education_ref", "niveau_education_ref")]
        public niveau_education_ref niveau_education_ref
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_education_ref>("SYSGERModel.FK_recrutements_niveau_education_ref", "niveau_education_ref").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_education_ref>("SYSGERModel.FK_recrutements_niveau_education_ref", "niveau_education_ref").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<niveau_education_ref> niveau_education_refReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_education_ref>("SYSGERModel.FK_recrutements_niveau_education_ref", "niveau_education_ref");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<niveau_education_ref>("SYSGERModel.FK_recrutements_niveau_education_ref", "niveau_education_ref", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_niveau_ref", "niveau_ref")]
        public niveau_ref niveau_ref
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_ref>("SYSGERModel.FK_recrutements_niveau_ref", "niveau_ref").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_ref>("SYSGERModel.FK_recrutements_niveau_ref", "niveau_ref").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<niveau_ref> niveau_refReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_ref>("SYSGERModel.FK_recrutements_niveau_ref", "niveau_ref");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<niveau_ref>("SYSGERModel.FK_recrutements_niveau_ref", "niveau_ref", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_niveau_ref1", "niveau_ref")]
        public niveau_ref niveau_ref1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_ref>("SYSGERModel.FK_recrutements_niveau_ref1", "niveau_ref").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_ref>("SYSGERModel.FK_recrutements_niveau_ref1", "niveau_ref").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<niveau_ref> niveau_ref1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<niveau_ref>("SYSGERModel.FK_recrutements_niveau_ref1", "niveau_ref");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<niveau_ref>("SYSGERModel.FK_recrutements_niveau_ref1", "niveau_ref", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYSGERModel", "FK_recrutements_position_ref", "position_ref")]
        public position_ref position_ref
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<position_ref>("SYSGERModel.FK_recrutements_position_ref", "position_ref").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<position_ref>("SYSGERModel.FK_recrutements_position_ref", "position_ref").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<position_ref> position_refReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<position_ref>("SYSGERModel.FK_recrutements_position_ref", "position_ref");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<position_ref>("SYSGERModel.FK_recrutements_position_ref", "position_ref", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYSGERModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
